name: Deploy to cPanel

on:
  push:
    paths:
      - dist/**
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'production'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install FTP Deployment Tool
        run: sudo apt-get install -y lftp

      - name: Deploy to cPanel
        run: |
          lftp -d -c "
          set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }}; 
          mirror -R --verbose --only-newer --parallel=10 ./dist /zazu;
          bye;
          "